/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import com.example.miapp.App;
import static org.junit.Assert.*;
import org.junit.Test;

public class AppTest {
    @Test
    public void testGetGreeting() {
        App classUnderTest = new App();
        // Llamar al método getGreeting y verificar que no sea null
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
